# image: https://hub.docker.com/_/xwiki
# docs: https://github.com/xwiki/xwiki-docker/blob/master/README.md

version: '3.8'

services:
  xwiki:
    image: xwiki:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - ${APP_HTTP_PORT}:8080
    volumes:
      - xwiki:/usr/local/xwiki
    environment:
      - DB_USER=${DB_MYSQL_USER}
      - DB_PASSWORD=${DB_MYSQL_PASSWORD}
      - DB_HOST=mysql
      - INDEX_HOST=solr
    links: 
      - mysql
      - solr
    restart: always

  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: xwiki-mysql
    restart: always
    ports:
     - ${DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${VOLUMES_PATH_PREFIX}/mysql/mysql_config/conf.d:/etc/mysql/conf.d
      - ${VOLUMES_PATH_PREFIX}/mysql/mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}

  solr:
    image: "solr:7.2"
    container_name: xwiki-solr
    volumes:
      - ./solr:/docker-entrypoint-initdb.d
      - solr:/opt/solr/server/solr
    expose:
      - "8983"

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  xwiki:
  solr:
  mysql:
